# Generated by Django 5.2.17 on 2026-08-30 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnatomyLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('body_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='core.bodysystem')),
            ],
            options={
                'ordering': ['body_system', 'order', 'name'],
                'unique_together': {('name', 'body_system')},
            },
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('model_name_3d', models.CharField(help_text='Maps to mesh name in GLB file', max_length=100)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('body_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organs', to='core.bodysystem')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organs', to='core.anatomylayer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('causes', models.TextField(blank=True, null=True)),
                ('treatments', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], default='mild', max_length=20)),
                ('prevalence', models.CharField(blank=True, max_length=100, null=True)),
                ('organ', models.ManyToManyField(related_name='diseases', to='core.organ')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('doi_url', models.URLField(blank=True, null=True)),
                ('pubmed_id', models.CharField(blank=True, max_length=50, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('disease', models.ManyToManyField(blank=True, related_name='research_papers', to='core.disease')),
            ],
            options={
                'ordering': ['-publication_date', 'title'],
            },
        ),
    ]
