# Generated by Django 5.2.17 on 2026-09-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anatomylayer',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Store translated fields like name and description in different languages'),
        ),
        migrations.AddField(
            model_name='bodysystem',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Store translated fields like name and description in different languages'),
        ),
        migrations.AddField(
            model_name='disease',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Store translated fields like name, description, symptoms, causes, and treatments in different languages'),
        ),
        migrations.AddField(
            model_name='organ',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Store translated fields like name and description in different languages'),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Store translated fields like title and abstract in different languages'),
        ),
    ]
